version: "3.8"
services:
  shop_api:
    container_name: shop_api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - shop_db

  shop_migrations:
    container_name: shop_migrations
    build:
      context: .
      dockerfile: Dockerfile
    command: "python manage.py migrate"
    depends_on:
      - shop_api

  shop_db:
    container_name: shop_db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: shop
      MYSQL_USER: my_user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
